; =*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=
;  Author: Florian Muecke
;  Copyright: Florian Muecke, 2005
;  Description: english language file for uneis
; =*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=

MsgAbout        DB "Easy (Un)Installation System v1.3.00",13,10,13,10
                DB "copyleft 2003-2005 Florian Mücke",13,10,13,10
                DB "greetings to:",13,10,"all MASM32 freaks",0
ask             DB "Really remove """,0
ask2            DB """ and all of its components?",0
ErrMsg          DB "no application specified for uneis",0
err1            DB "error accessing registry value",0
ConsoleTitle    DB "remove application",0
ConsoleTitle2   DB "deinstallation complete",0
ConsoleSTitle   DB "The application is being removed from your system...",0
ConsoleSTitle2  DB "The deinstallation is complete.",13,10,"You can leave the program now by clicking the ""Finish"" button.",0
AboutStr        DB "about EIS...",0
