; =*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=
;  Author: Florian Muecke
;  Copyright: Florian Muecke, 2005
;  Description: german language file for uneis
; =*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=

MsgAbout        DB "Easy (Un)Installation System v1.3.00",13,10,13,10
                DB "Copyleft 2003-2005 Florian Mücke",13,10,13,10
                DB "Greetings to:",13,10,"alle MASM32 freaks, team EVO",0
ask             DB "Wollen Sie wirklich """,0
ask2            DB """ und all seine Komponenten entfernen?",0
ErrMsg          DB "keine Applikation zum Deinstallieren angegeben",0
err1            DB "Fehler beim Zugriff auf die Registrierdatenbank",0
ConsoleTitle    DB "Anwendung Entfernen",0
ConsoleTitle2   DB "Deinstallation abgeschlossen",0
ConsoleSTitle   DB "Die Anwendung wird von Ihrem System entfernt...",0
ConsoleSTitle2  DB "Die Deinstallation ist abgeschlossen.",13,10,"Sie können das Programm jetzt mit Fertig stellen verlassen.",0
AboutStr        DB "Über EIS...",0
